[mgr]
prepend_keymap = [
	{ on = "e", run = "shell \"code %h\" --orphan", desc = "Open hovered in VS Code" },
	{ on = "b", run = "shell \"explorer /select,%h\" --orphan", desc = "Reveal hovered in Explorer", for = "windows" },
	{ on = "b", run = "shell \"open -R %h\" --orphan", desc = "Reveal hovered in Finder", for = "macos" },
	{ on = "u", run = "copy path --hovered", desc = "Copy hovered path" },
	{ on = "C", run = "shell \"tar -a -c -f archive.zip %s\" --block", desc = "Zip selection" },
	{ on = "i", run = "plugin save-tabs", desc = "Save tabs" },
	{ on = "<C-p>", run = "shell \"start \"\" %h\"", desc = "Open hovered with default app", for = "windows" },
	{ on = "<C-p>", run = "shell -- qlmanage -p %s", desc = "Preview files with the system Quick Look", for = "macos" },
	{ on = "!", run = "shell \"pwsh\" --block", for = "windows", desc = "Open pwsh here" },
	{ on = "!", run = "shell \"$SHELL\" --block", for = "unix", desc = "Open $SHELL here" },
]
